# Generated by Django 4.0.2 on 2022-02-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='KRMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kr_id', models.CharField(default='', max_length=70)),
                ('workitem_ids', models.CharField(default='', max_length=70)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField()),
            ],
        ),
    ]
