# Generated by Django 4.0.2 on 2022-02-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='krmap',
            old_name='kr_id',
            new_name='identifier',
        ),
        migrations.RemoveField(
            model_name='krmap',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='connection',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='krmap',
            name='workitem_ids',
            field=models.JSONField(null=True),
        ),
    ]
