# Generated by Django 4.0.2 on 2022-02-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_kr_id_krmap_identifier_remove_krmap_metadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='metadata',
            new_name='meta_data',
        ),
    ]
