# Generated by Django 4.0.2 on 2022-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_connection_meta_data_alter_krmap_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='id',
        ),
        migrations.AlterField(
            model_name='connection',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
