# Generated by Django 4.0.2 on 2022-02-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_connection_id_alter_connection_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='type',
            field=models.CharField(default='excel365', max_length=70),
        ),
    ]
